### ISSUE TITLE
Some errors with components

### ISSUE THREAD

**Issue by iamwhitebox** [patrickbolle/vue-todo#1]
Hello, I am getting error with several components when running "npm run dev" after other instructions, please advise:

<img width="543" alt="screen shot 2016-09-07 at 6 02 39 am" src="https://cloud.githubusercontent.com/assets/13710868/18312937/02e8484a-74c1-11e6-9493-52d4940d5e8b.png">

Which version of nodejs do you recommend?

**Comment by patrickbolle** [comment]
Hey! My bad, I didn't include all of the dependencies. You can run 

```
npm install --save vue-router vue-resource 
```

to fix that.
I'll upload a new version anyways with the fix.

**Comment by patrickbolle** [comment]
This should work. 
bd7458d579e8692e10d65ddf8b074a9df74a231b

In the master now, so just do a pull.

Working on improving this by the way, I'll be adding user authentication and cleaning up the code soon.
